# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/malkmusl/Development/cpp/multithread_test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/malkmusl/Development/cpp/multithread_test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/malkmusl/Development/cpp/multithread_test/CMakeFiles /home/malkmusl/Development/cpp/multithread_test//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/malkmusl/Development/cpp/multithread_test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named malkmusl_engine_cpp

# Build rule for target.
malkmusl_engine_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 malkmusl_engine_cpp
.PHONY : malkmusl_engine_cpp

# fast build rule for target.
malkmusl_engine_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/malkmusl_engine_cpp.dir/build.make CMakeFiles/malkmusl_engine_cpp.dir/build
.PHONY : malkmusl_engine_cpp/fast

#=============================================================================
# Target rules for targets named _system

# Build rule for target.
_system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _system
.PHONY : _system

# fast build rule for target.
_system/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_system.dir/build.make CMakeFiles/_system.dir/build
.PHONY : _system/fast

#=============================================================================
# Target rules for targets named _logger

# Build rule for target.
_logger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _logger
.PHONY : _logger

# fast build rule for target.
_logger/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_logger.dir/build.make CMakeFiles/_logger.dir/build
.PHONY : _logger/fast

#=============================================================================
# Target rules for targets named _hot_reload

# Build rule for target.
_hot_reload: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _hot_reload
.PHONY : _hot_reload

# fast build rule for target.
_hot_reload/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_hot_reload.dir/build.make CMakeFiles/_hot_reload.dir/build
.PHONY : _hot_reload/fast

src/logger/logger.o: src/logger/logger.cpp.o
.PHONY : src/logger/logger.o

# target to build an object file
src/logger/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_logger.dir/build.make CMakeFiles/_logger.dir/src/logger/logger.cpp.o
.PHONY : src/logger/logger.cpp.o

src/logger/logger.i: src/logger/logger.cpp.i
.PHONY : src/logger/logger.i

# target to preprocess a source file
src/logger/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_logger.dir/build.make CMakeFiles/_logger.dir/src/logger/logger.cpp.i
.PHONY : src/logger/logger.cpp.i

src/logger/logger.s: src/logger/logger.cpp.s
.PHONY : src/logger/logger.s

# target to generate assembly for a file
src/logger/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_logger.dir/build.make CMakeFiles/_logger.dir/src/logger/logger.cpp.s
.PHONY : src/logger/logger.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/malkmusl_engine_cpp.dir/build.make CMakeFiles/malkmusl_engine_cpp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/malkmusl_engine_cpp.dir/build.make CMakeFiles/malkmusl_engine_cpp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/malkmusl_engine_cpp.dir/build.make CMakeFiles/malkmusl_engine_cpp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/system/core/hot_reload_system.o: src/system/core/hot_reload_system.cpp.o
.PHONY : src/system/core/hot_reload_system.o

# target to build an object file
src/system/core/hot_reload_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_hot_reload.dir/build.make CMakeFiles/_hot_reload.dir/src/system/core/hot_reload_system.cpp.o
.PHONY : src/system/core/hot_reload_system.cpp.o

src/system/core/hot_reload_system.i: src/system/core/hot_reload_system.cpp.i
.PHONY : src/system/core/hot_reload_system.i

# target to preprocess a source file
src/system/core/hot_reload_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_hot_reload.dir/build.make CMakeFiles/_hot_reload.dir/src/system/core/hot_reload_system.cpp.i
.PHONY : src/system/core/hot_reload_system.cpp.i

src/system/core/hot_reload_system.s: src/system/core/hot_reload_system.cpp.s
.PHONY : src/system/core/hot_reload_system.s

# target to generate assembly for a file
src/system/core/hot_reload_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_hot_reload.dir/build.make CMakeFiles/_hot_reload.dir/src/system/core/hot_reload_system.cpp.s
.PHONY : src/system/core/hot_reload_system.cpp.s

src/system/system.o: src/system/system.cpp.o
.PHONY : src/system/system.o

# target to build an object file
src/system/system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_system.dir/build.make CMakeFiles/_system.dir/src/system/system.cpp.o
.PHONY : src/system/system.cpp.o

src/system/system.i: src/system/system.cpp.i
.PHONY : src/system/system.i

# target to preprocess a source file
src/system/system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_system.dir/build.make CMakeFiles/_system.dir/src/system/system.cpp.i
.PHONY : src/system/system.cpp.i

src/system/system.s: src/system/system.cpp.s
.PHONY : src/system/system.s

# target to generate assembly for a file
src/system/system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_system.dir/build.make CMakeFiles/_system.dir/src/system/system.cpp.s
.PHONY : src/system/system.cpp.s

src/system/utils/state_name.o: src/system/utils/state_name.cpp.o
.PHONY : src/system/utils/state_name.o

# target to build an object file
src/system/utils/state_name.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_system.dir/build.make CMakeFiles/_system.dir/src/system/utils/state_name.cpp.o
.PHONY : src/system/utils/state_name.cpp.o

src/system/utils/state_name.i: src/system/utils/state_name.cpp.i
.PHONY : src/system/utils/state_name.i

# target to preprocess a source file
src/system/utils/state_name.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_system.dir/build.make CMakeFiles/_system.dir/src/system/utils/state_name.cpp.i
.PHONY : src/system/utils/state_name.cpp.i

src/system/utils/state_name.s: src/system/utils/state_name.cpp.s
.PHONY : src/system/utils/state_name.s

# target to generate assembly for a file
src/system/utils/state_name.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_system.dir/build.make CMakeFiles/_system.dir/src/system/utils/state_name.cpp.s
.PHONY : src/system/utils/state_name.cpp.s

src/system/utils/system_factory.o: src/system/utils/system_factory.cpp.o
.PHONY : src/system/utils/system_factory.o

# target to build an object file
src/system/utils/system_factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_system.dir/build.make CMakeFiles/_system.dir/src/system/utils/system_factory.cpp.o
.PHONY : src/system/utils/system_factory.cpp.o

src/system/utils/system_factory.i: src/system/utils/system_factory.cpp.i
.PHONY : src/system/utils/system_factory.i

# target to preprocess a source file
src/system/utils/system_factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_system.dir/build.make CMakeFiles/_system.dir/src/system/utils/system_factory.cpp.i
.PHONY : src/system/utils/system_factory.cpp.i

src/system/utils/system_factory.s: src/system/utils/system_factory.cpp.s
.PHONY : src/system/utils/system_factory.s

# target to generate assembly for a file
src/system/utils/system_factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_system.dir/build.make CMakeFiles/_system.dir/src/system/utils/system_factory.cpp.s
.PHONY : src/system/utils/system_factory.cpp.s

src/system/utils/system_manager.o: src/system/utils/system_manager.cpp.o
.PHONY : src/system/utils/system_manager.o

# target to build an object file
src/system/utils/system_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_system.dir/build.make CMakeFiles/_system.dir/src/system/utils/system_manager.cpp.o
.PHONY : src/system/utils/system_manager.cpp.o

src/system/utils/system_manager.i: src/system/utils/system_manager.cpp.i
.PHONY : src/system/utils/system_manager.i

# target to preprocess a source file
src/system/utils/system_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_system.dir/build.make CMakeFiles/_system.dir/src/system/utils/system_manager.cpp.i
.PHONY : src/system/utils/system_manager.cpp.i

src/system/utils/system_manager.s: src/system/utils/system_manager.cpp.s
.PHONY : src/system/utils/system_manager.s

# target to generate assembly for a file
src/system/utils/system_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_system.dir/build.make CMakeFiles/_system.dir/src/system/utils/system_manager.cpp.s
.PHONY : src/system/utils/system_manager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... _hot_reload"
	@echo "... _logger"
	@echo "... _system"
	@echo "... malkmusl_engine_cpp"
	@echo "... src/logger/logger.o"
	@echo "... src/logger/logger.i"
	@echo "... src/logger/logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/system/core/hot_reload_system.o"
	@echo "... src/system/core/hot_reload_system.i"
	@echo "... src/system/core/hot_reload_system.s"
	@echo "... src/system/system.o"
	@echo "... src/system/system.i"
	@echo "... src/system/system.s"
	@echo "... src/system/utils/state_name.o"
	@echo "... src/system/utils/state_name.i"
	@echo "... src/system/utils/state_name.s"
	@echo "... src/system/utils/system_factory.o"
	@echo "... src/system/utils/system_factory.i"
	@echo "... src/system/utils/system_factory.s"
	@echo "... src/system/utils/system_manager.o"
	@echo "... src/system/utils/system_manager.i"
	@echo "... src/system/utils/system_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

